dvd_rentals:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SF_ACC') }}"
      # User/password auth
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASS') }}"
      role: "{{ env_var('SF_ROLES') }}"
      database: dvd_rentals
      warehouse: compute_wh
      schema: marts
      threads: 2
      client_session_keep_alive: False