dvd_rentals:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: QLZGDCF-SC02516 # "{{ env_var('SF_ACC') }}"
      # User/password auth
      user: BGEO # "{{ env_var('SF_USER') }}"
      password: c1XA04k2AAAAAA # "{{ env_var('SF_PASS') }}"
      role: accountadmin
      database: dvd_rentals
      warehouse: compute_wh
      schema: transformation
      threads: 8
      client_session_keep_alive: False